### PR TITLE
First pass at CLI documentation formatting fixes

### LINKED ISSUE #102: Misformatted command documentation
Some commands look misformatted when displayed in Markdown. Ex: 

```
  # Initialize a new staging environment at 'us-west'.
	# The environment will be setup using the current context in your kubecfg file. The directory
	# structure rooted at 'us-west' in the documentation above will be generated.
  ks env add us-west/staging
```

Go through and fix them.

### PR DESCRIPTION
**Pull request by jessicayuen**
Fixes #102 

The easiest way to review this is probably by traversing the UI located at my [fork](https://github.com/jessicayuen/ksonnet/tree/format-commands/docs/cli-reference#command-line-reference).

### CODE REVIEW

File: cmd/apply.go [hunk 1]
```diff
@@ -121,28 +121,28 @@ var applyCmd = &cobra.Command{
...
+# running in the 'dev' environment. Can be used in any subdirectory of the
+# application.
+ks apply dev
 
-  # Create or update resources described in a YAML file. Automatically picks up
-  # the cluster's location from '$KUBECONFIG'.
-  ks appy -f ./pod.yaml
+# Create or update resources described in a YAML file. Automatically picks up
+# the cluster's location from '$KUBECONFIG'.
+ks appy -f ./pod.yaml
```
Comment (abiogenesis-now) [inline cmd/apply.go]: s/appy/apply while we're here

File: cmd/diff.go [hunk 2]
```diff
@@ -88,35 +88,35 @@ configurations.
...
-  # referenced by the environment 'dev'.
-  ks diff dev -f ./pod.json
-
-  # Show diff between resources described in a YAML file and the cluster
-  # referred to by './kubeconfig'.
-  ks diff --kubeconfig=./kubeconfig -f ./pod.yaml`,
+	Example: `# Show diff between resources described in a the local 'dev' environment
+# specified by the ksonnet application and the remote cluster referenced by
+# the same 'dev' environment. Can be used in any subdirectory of the application.
+ksonnet diff dev
```
Comment (abiogenesis-now) [inline cmd/diff.go]: change to `ks` (plus the two commands below as well

File: cmd/env.go [hunk 3]
```diff
@@ -56,7 +56,7 @@ var envCmd = &cobra.Command{
 	Use:   "env",
 	Short: `Manage ksonnet environments`,
 	Long: `An environment acts as a sort of "named cluster", allowing for commands like
-'ks apply dev', which applies the ksonnet application to the "dev cluster".
+` + " `ks apply dev` " + `, which applies the ksonnet application to the 'dev cluster'.
```
Comment (abiogenesis-now) [inline cmd/env.go]: nit: can we use double quotes for "dev cluster" to be consistent?

File: cmd/env.go [hunk 4]
```diff
@@ -68,25 +68,27 @@ often contained in a kubeconfig file), and
 Environments are represented as a hierarchy in the 'environments' directory of a
 ksonnet application. For example, in the example below, there are two
 environments: 'default' and 'us-west/staging'. Each contains a cached version of
```
Comment (abiogenesis-now) [inline cmd/env.go]: sorry to be a pain, but can you make these double quotes as well
