### PR TITLE
param set should understand module dot paths

### LINKED ISSUE #642: Setting parameters in modules doesn’t understand dot notation
/kind bug

Modules are identified with a dot path: `apps.name.component`. When setting parameters, you be able to use the dot path: `ks param set apps.name.component field value`.

This doesn't work, but using slashes does.

### PR DESCRIPTION
**Pull request by bryanl**
Fixes #642

Signed-off-by: bryanl <bryanliles@gmail.com>

### CODE REVIEW

File: pkg/component/manager.go [hunk 1]
```diff
@@ -24,37 +24,38 @@ import (
...
 
-		return ns, nil, nil
+		return m, nil, nil
 	}
 
-	module, cName, err := checkComponent(ksApp, path)
+	moduleName, componentName, err := extractPathParts(ksApp, path)
 	if err != nil {
-		return nil, nil, err
+		return nil, nil, errors.Wrapf(err, "checking component %s", path)
```
Comment (underrun) [inline pkg/component/manager.go]: "extracting path parts" instead of checking component to match new function name

File: pkg/component/manager.go [hunk 2]
```diff
@@ -24,37 +24,38 @@ import (
...
-			return nil, nil, err
+			return nil, nil, errors.Wrapf(err, "retrieving module %s", path)
 		}
 
-		return ns, nil, nil
+		return m, nil, nil
 	}
 
-	module, cName, err := checkComponent(ksApp, path)
+	moduleName, componentName, err := extractPathParts(ksApp, path)
```
Comment (underrun) [inline pkg/component/manager.go]: we're passing `path` in as `name` to extractPathParts ... if we've gotten here then `path` is not a path. previous to here `path` could actually be a path (if isDir is true it's an actual path right?) ... i feel like `name` feels better all the way up on this where `name` could be a path and you early out if it is.

File: pkg/component/manager_test.go [hunk 3]
```diff
@@ -52,29 +52,32 @@ func Test_ResolvePath(t *testing.T) {
...
-			isErr  bool
+			name              string
+			expectedComponent string
+			expectedModule    string
+			isErr             bool
 		}{
 			{
-				name:   "/",
-				module: "/",
+				name:           "/",
```
Comment (underrun) [inline pkg/component/manager_test.go]: so .. this works, but contextually being able to specify a path with / in it to ResolvePath but also that names cannot have / in them feels a bit rough to me - can we go all dots?

File: pkg/component/manager_test.go [hunk 4]
```diff
@@ -52,29 +52,32 @@ func Test_ResolvePath(t *testing.T) {
...
-				cName:  "deployment",
+				name:              "nested.deployment",
+				expectedModule:    "nested",
+				expectedComponent: "deployment",
 			},
 			{
-				name:   "nested/deployment",
-				module: "nested",
-				cName:  "deployment",
+				name:           "nested",
```
Comment (underrun) [inline pkg/component/manager_test.go]: this test is not nested and the case is also covered in "deployment" we should remove this test

File: pkg/component/manager.go (hunk 1 above)
Comment (bryanl) [reply pkg/component/manager.go]: I replaced it with "extracting module and component names from %s"

File: pkg/component/manager_test.go (hunk 3 above)
Comment (bryanl) [reply pkg/component/manager_test.go]: I thought about all dots, but having one named "." felt weird to me, so I left it as "/".

File: pkg/component/manager.go (hunk 2 above)
Comment (bryanl) [reply pkg/component/manager.go]: It's a path and not a name. I updated the function.
