### PR TITLE
Accurately read/write non-ASCII param identifiers

### LINKED ISSUE #214: `param set` incorrectly supporting hyphenated param names
Ex:
`ks param set guestbook-ui foo-bar 5`

is outputting jsonnet
```
  components: {
    // Component-level parameters, defined initially from 'ks prototype use ...'
    // Each object below should correspond to a component in the components/ directory
    "guestbook-ui": {
      foo-bar: 20,
    },
  },
```

`foo-bar` needs to be quoted.

### PR DESCRIPTION
**Pull request by jessicayuen**
**Fixes #214**

Currently, if we run `param set guestbook-ui foo-bar x`,

The jsonnet snippet will write: `foo-bar: "x"`.

However, this is incorrect jsonnet syntax. This commit will fix this
issue, to instead write `"foo-bar": "x"`.

Also updates the `Get...` Param functions to return non-quoted
identifiers for prettier display.

Signed-off-by: Jessica Yuen <im.jessicayuen@gmail.com>

### CODE REVIEW

File: utils/strings.go [hunk 1]
```diff
@@ -34,6 +35,14 @@ func IsASCIIIdentifier(s string) bool {
 	return true
 }
 
+// QuoteNonASCII puts quotes around a identifiers that contain non-ASCII characters.
```
Comment (jessicayuen) [inline utils/strings.go]: note to self for wednesday: grammar!
